server:
  port: 8080
spring:
  application:
    name: gateway-service
  jackson:
    default-property-inclusion: non_null
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: secretkey
